name: Pacific Breeze Marianita
favicon: null
layout_spectrum: 0.5700055821798742
typography_spectrum: 0.21053342637605965
title: 'Affordable Town-Houses on the Beach!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9318201972637326
  lightness: 0.5646521314047277
  saturation: 0.9227024426218122
  rhythmicContrast: 0.41785164806060493
purpose: []
